### ISSUE TITLE
Missing icons in the application interface

### ISSUE THREAD

**Issue by animegamer4422** [staniel359/muffon#116]
## Description
There appears to be a graphical issue where several icons are missing from the user interface within the Muffon application. This issue is observed in the menu items and buttons where icons are expected to be seen.

## Expected Behavior
All buttons and menu items should display their respective icons to ensure users can navigate the application intuitively.

## Actual Behavior
Icons for various buttons and menu items are not being displayed. This includes icons on the side navigation menu and possibly other interface elements where placeholders or blank spaces are shown instead.

## Steps to Reproduce
1. Open the Muffon application.
2. Observe the missing icons in the side navigation menu and other areas.

## Screenshots
Here are the screenshots that illustrate the issue:

![Missing Icons - Screenshot 1](https://github.com/staniel359/muffon/assets/71986052/0419fd9f-6b4c-41e4-a553-995faca78398)
![Missing Icons - Screenshot 2](https://github.com/staniel359/muffon/assets/71986052/8e7e1f88-a5b5-48f6-91ae-ff46b7d9a1aa)

## Environment
- **Operating System:** Windows 11 (Latest version)
- **Muffon Version:** 2.0.0 (Downloaded from the project homepage)

## Additional Context
The missing icons issue has a significant impact on the usability of the app, as it makes navigation and functionality less intuitive for users.

Thank you for your attention to this matter.

**Comment by gamersi** [comment]
There is currently a problem with the image store on the server.
Staniel is working hard on a fix. I can't give any information on when it is coming as the scale of the issue is not yet fully known.
For further information and future maintenance alerts refer to the discord and this message: https://discord.com/channels/1023883455504850974/1145822248364687381/1171447022189035570

@staniel359 do you want to add something?

Thank you for taking the time  to write a report an have a nice rest of your day

**Comment by xyloflake** [comment]
Hi! Muffon dev here. The problem is basically that the images on the server got *accidentally deleted*. We have restored the images but right now, Staniel, the creator is working on a fix on restoring the restored images with their respective structure. Until we restore the image files structure, we have no choice but to shut down the image service to prevent further loss.


We are extremely sorry for the inconvenience and as @gamersi suggested, you should join the discord server if possible for getting updates. 

Thank you.

**Comment by staniel359** [comment]
@gamersi @xyloflake You guys know that icons are related to font, not images?

**Comment by gamersi** [comment]
> @gamersi @xyloflake You guys know that icons are related to font, not images?

Yeah but fonts are normally not a problem on windows

**Comment by staniel359** [comment]
@animegamer4422 Hello.
The issue is related to font (Lato), but I don't know what's the cause yet.
Maybe you have it installed on your system?

**Comment by xyloflake** [comment]
I tried deleting the lato font on my laptop but that didn't cause it the *icons* to break, only the font.

**Comment by animegamer4422** [comment]
> @animegamer4422 Hello. The issue is related to font (Lato), but I don't know what's the cause yet. Maybe you have it installed on your system?

i didn't had it installed
but i also tried installing it to see what happens and it made no changes to muffon (also i restarted after installing the fonts of course)

installed lato from (https://fonts.google.com/specimen/Lato)

**Comment by staniel359** [comment]
@animegamer4422 So what was the problem?

**Comment by staniel359** [comment]
@animegamer4422 Did you use installer or portable?

**Comment by animegamer4422** [comment]
@staniel359 Installer as mentioned in the first comment

**Comment by staniel359** [comment]
@animegamer4422 This wasn't mentioned exactly.
Could you try portable version?

**Comment by animegamer4422** [comment]
@staniel359 
Sure , just give me a moment

**Comment by animegamer4422** [comment]
@staniel359 
The portable version doesn't has this issue
 It works as expected and shows all icons

![Screenshot of the portable version](https://github.com/staniel359/muffon/assets/71986052/d2c99ade-34b2-4736-8ec9-b45f4477e7d2)

**Comment by staniel359** [comment]
@animegamer4422 Thanks.
Could you check, maybe your Windows Defender has blocked some of app's files?

**Comment by animegamer4422** [comment]
@staniel359 
I reinstalled using the same installer package (2.0.0) and the issue doesn't seems to appear anymore

sorry for the inconvenience i caused

![Muffon Installed Screenshot](https://github.com/staniel359/muffon/assets/71986052/de67fdb8-695c-40dd-83b7-6604637e72f1)

**Comment by xyloflake** [comment]
@gamersi can this be a cache issue (again)? We disabled it ig. @staniel359 are the icons cached?

**Comment by staniel359** [comment]
@xyloflake Cache is disabled.
And icons come with build files, along with other assets (images, styles, js).

**Comment by gamersi** [comment]
> @xyloflake Cache is disabled.
> 
> And icons come with build files, along with other assets (images, styles, js).

I think something went wrong during inatallation on his PC 
maybe he has some kind of AV/similar

**Comment by xyloflake** [comment]
> > @xyloflake Cache is disabled.
> > 
> > And icons come with build files, along with other assets (images, styles, js).
> 
> I think something went wrong during inatallation on his PC 
> maybe he has some kind of AV/similar

I think you are quite right, maybe during installation his computer couldn't copy the assets from the installer. Also @animegamer4422 when did you download this? @staniel359 maybe he downloaded the prerelease when it was made public for the beta testers, when cache wasn't disabled. Anyways, this issue should be closed now.

**Comment by animegamer4422** [comment]
@gamersi 
I don't have any External AV's , i only have got windows defender

@xyloflake 
I downloadee it from the project homepage last week (the same day I put up this issue)
And also it was not a beta as I downloaded it from
https://muffon.netlify.app/

**Comment by xyloflake** [comment]
> @gamersi 
> 
> I don't have any External AV's , i only have got windows defender
> 
> 
> 
> @xyloflake 
> 
> I downloadee it from the project homepage last week (the same day I put up this issue)
> 
> And also it was not a beta as I downloaded it from
> 
> https://muffon.netlify.app/

Sorry, just because you downloaded it from the website doesn't mean it necessarily isn't a beta since we don't have indicators for beta releases, I don't know if prereleases are published on the website though, @staniel359 would know so I'd let him answer this. But I don't think just because you downloaded from the website means that it's not beta.

Also, we have made beta releases private and only available to our discord members who signed up for the beta program, so this is not likely to happen in the future, betas have a lot of bugs and this happened like a month ago when the beta releases had a lot of bugs but a prerelease was made and later deleted, the main bug was a caching problem which I discovered when I dug into the machine and assembly code, which was causing the login page to not work because the requests were cached when the server for 2.0.0 wasn't ready and started, so I recommended everyone who had it to reinstall it, and that fixed it, so we next used the flag "--disable-http-cache" for the next build which disabled the http caching. 

# This might be an icons caching issue
## We disabled it only for *HTTP* not for images/icons and no HTTP request is made for fetching the icons

One more possibility would be that the installer didn't extract the images correctly while installing, this is really hard to replicate.

### Also, since he says he downloaded it a week ago, this is definitely not in that beta period, this might be a caching issue that is related to images/icons OR might be some installer problem. I think I'll dig into the machine and assembly code to find out what happened.

Thanks @animegamer4422, you may close this issue now since your issue is solved, if I find a problem with the machine code, I'll reopen this.

![image](https://github.com/staniel359/muffon/assets/142194553/7ad342e4-e450-4559-8efd-53e1268c58ae)

**Comment by animegamer4422** [comment]
@xyloflake 
Also i forgot to add
I reinstalled muffon using the same file as earlier
 But the first time there were no icons and after i deleted and reinstalled the icons were there

So probably something went wrong during installation and some stuff didn't got copied which was needed for the icons
That's about everything that I think has happened

**Comment by animegamer4422** [comment]
Thanks for everyone for looking into this
 I'm sorry for wasting developer time over nothing
 Have a great day ahead

**Comment by xyloflake** [comment]
> @xyloflake 
> 
> Also i forgot to add
> 
> I reinstalled muffon using the same file as earlier
> 
>  But the first time there were no icons and after i deleted and reinstalled the icons were there
> 
> 
> 
> So probably something went wrong during installation and some stuff didn't got copied which was needed for the icons
> 
> That's about everything that I think has happened 

Doesn't matter since we never disabled caching for image, not a beta problem. But thanks.

**Comment by staniel359** [comment]
@xyloflake If it was downloaded last week, then it was way after beta release.

**Comment by staniel359** [comment]
@animegamer4422 No problem!

But the reason is still unknown.
If something would've happened during installation, you'd get an error and a rollback.
I'll reopen this if someone else has the same problem in future.

**Comment by xyloflake** [comment]
> @xyloflake If it was downloaded last week, then it was way after beta release.

Exactly what I said! I think the installers have some problem with windows.

**Comment by gamersi** [comment]
> > @xyloflake If it was downloaded last week, then it was way after beta release.
> 
> Exactly what I said! I think the installers have some problem with windows.

I think windows is the problem (sorry fanboys)
