### ISSUE TITLE
Замедление скорости воспроизведения

### ISSUE THREAD

**Issue by ormgard** [staniel359/muffon#129]
При физической конфигурации динамиков 4.0, 5.1 скорость воспроизведения музыки падает вдвое(

**Comment by xyloflake** [comment]
# Translation
## Decreased playback speed 
With a physical configuration of speakers in 4.0 or 5.1, the music playback speed decreases by half.

**Comment by xyloflake** [comment]
@ormgard Можете быть конкретнее относительно того, что вы имеете в виду? Это очень неясно, что вы говорите.


Translation: @ormgard Can you be specific about what you mean? It’s very unclear about what you’re saying.

**Comment by ormgard** [comment]
звучание меняется.
https://github.com/staniel359/muffon/assets/96700140/1d108d72-dacb-44de-ae8b-306a26439a42

**Comment by staniel359** [comment]
@ormgard Приветствую.
После переключения перезапускать не пробовали?

**Comment by ormgard** [comment]
> После переключения перезапускать не пробовали?

пробовал перезапускать. все равно искажения остаются.

**Comment by xyloflake** [comment]
@ormgard Версия Windows, которую вы используете, некорректна. Ваша панель задач выглядит как в Windows 11, но приложение настроек принадлежит Windows 10. Предполагаю, что у вас установлена предварительная версия Windows 11 (которая была довольно ошибочной). Пожалуйста, обновитесь до более новой версии и дайте нам знать, была ли проблема решена.

Кстати: У нас нет никакого отношения к аудио, мы передаем его браузеру Chromium, который работает на платформе Electron. Так что любая проблема, с которой вы сталкиваетесь, связана с некорректными настройками аудио в системе или может быть связана с ошибками в Chromium, о которых мы не знаем. Можете ли вы воспроизвести аудио через браузер Chrome с теми же настройками без ошибок?


## Translation
The version of windows you’re using is faulty, your taskbar looks like it’s Windows 11 but the settings app is from Windows 10. I believe you’ve got the Windows 11 pre release (which was really buggy). Please update to a newer version and let us know if the problem was solved. 

Side note: We have nothing to do with the audio, we pass it on to the Chromium browser which runs Electron. So whatever problem you’re facing is because of the faulty system audio configs or chromium has some bugs we didn’t know about. Can you play some audio from Chrome Browser with the same audio config without any bugs?

**Comment by ormgard** [comment]
> Версия Windows, которую вы используете, некорректна

обычная win11 23h2 канал-стабильный


> приложение настроек принадлежит Windows 10

драйвер UAD и панель управления звуком  Realtek из Microsoft Store

> Можете ли вы воспроизвести аудио через браузер Chrome с теми же настройками без ошибок?

через хром замечаний нет, все работает.

**Comment by xyloflake** [comment]
@ormgard Hmm, это интересно. Я посмотрю, спасибо за обратную связь. @gamersi может попробовать воспроизвести проблему.


## Translation
Hmm, that’s interesting, I’ll have a look, thank you for reporting. @gamersi can try reproducing the issue.

**Comment by xyloflake** [comment]
Cпасибо @ormgard за сообщение об этом. Это было довольно интересное событие в последнее время. Проблема была устранена, теперь можно закрыть @staniel359.

## Translation
Thank you @ormgard for reporting this. This was a rather interesting one we’ve got in a while. The issue has been fixed, this can be closed now @staniel359

**Comment by staniel359** [comment]
@ormgard Как и сказано выше, проблема была найдена.
Исправление будет в следующей версии.
