### ISSUE TITLE
Ability to hide artist in library for recommendations

### ISSUE THREAD

**Issue by maxsubs** [staniel359/muffon#51]
I use Muffon mostly for the recommendations. I've imported my Last.FM library, but when I go to Recommendations I have to manually hide the artists that already are on my library. It would be nice if it were possible to filter artists already on my library with more than X songs/scrobbles "Hide recommendations with more than 5/15/30... songs in your library". Just an idea, don't know if it'd be easy to implement. Thanks!

**Comment by staniel359** [comment]
@maxsubs Hello.
I had an idea of an option to hide recommendations if they're in library or in listened artists.
Just didn't add it yet.
Is it important to consider number of artist's songs for this?

**Comment by ch-rs** [comment]
Hi. I've been testing this and here's my two cents.

The way Last.FM works means you can end up with a lot of unknown artists in your library. With a library imported from Last.FM, an artist can be in your library if you've only listened to a single track one time. If you exclude all in-library artists from recommendations, anything you've listened to at all in the past wouldn't show up.

Let's say there's an track Last.FM recommended to you 5 years ago and you didn't take to the track. You may still like the artist's other tracks, but that artist would be in your muffon library (if you imported your Last.FM library) and would be excluded from muffon recommendations based on that one scrobble. 

That's why the scrobble threshold is a smart idea, in order to prevent those false exclusions. It wouldn't work quite as well by checking number of artists songs, since you may listen to only 1 or 2 songs from an artist in your library and have lots of plays.

It's not a huge deal though. An alternative would be to go through your muffon library artists and delete the ones you don't recognise, to ensure they can be recommened to you again. Though that is a little tedious. 

One could argue that it would be better if those one-off single scrobble artists weren't imported to muffon in the first place.

For now I think just excluding any artists already in your library would be a big win on its own.

**Comment by maxsubs** [comment]
Exactly what @ch-rs has said. I have been using Last.FM since 2005, so the amount of 1-5 song artists of which I know (close to) nothing of them is huge. I'd prefer the idea of filtering them by songs in library, over deleting them from my library, or not importing them, since I'd like to know that I have already listened to them.
But yes, excluding artists would be an improvement at any rate :)

**Comment by staniel359** [comment]
@ch-rs @maxsubs I got your point.
So there will be an option to
`Hide artists from my library`
with optional field
`with number of tracks more than {number}`.
